# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MraidExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MraidExample
	
pod 'MraidSDK',:git => "https://github.com/hexims/MraidSDK.git",:tag => '1.0.0'

end
